### ISSUE TITLE
ipapi AttributeError

### ISSUE THREAD

**Issue by wichert** [mverteuil/pytest-ipdb#15]
I ran into this exception:

```
INTERNALERROR> Traceback (most recent call last):
INTERNALERROR>   File "/Users/wichert/Library/buildout/eggs/pytest-2.4.2-py2.7.egg/_pytest/main.py", line 81, in wrap_session
INTERNALERROR>     doit(config, session)
INTERNALERROR>   File "/Users/wichert/Library/buildout/eggs/pytest-2.4.2-py2.7.egg/_pytest/main.py", line 117, in _main
INTERNALERROR>     config.hook.pytest_runtestloop(session=session)
INTERNALERROR>   File "/Users/wichert/Library/buildout/eggs/pytest-2.4.2-py2.7.egg/_pytest/core.py", line 368, in __call__
INTERNALERROR>     return self._docall(methods, kwargs)
INTERNALERROR>   File "/Users/wichert/Library/buildout/eggs/pytest-2.4.2-py2.7.egg/_pytest/core.py", line 379, in _docall
INTERNALERROR>     res = mc.execute()
INTERNALERROR>   File "/Users/wichert/Library/buildout/eggs/pytest-2.4.2-py2.7.egg/_pytest/core.py", line 297, in execute
INTERNALERROR>     res = method(**kwargs)
INTERNALERROR>   File "/Users/wichert/Library/buildout/eggs/pytest-2.4.2-py2.7.egg/_pytest/main.py", line 137, in pytest_runtestloop
INTERNALERROR>     item.config.hook.pytest_runtest_protocol(item=item, nextitem=nextitem)
INTERNALERROR>   File "/Users/wichert/Library/buildout/eggs/pytest-2.4.2-py2.7.egg/_pytest/core.py", line 368, in __call__
INTERNALERROR>     return self._docall(methods, kwargs)
INTERNALERROR>   File "/Users/wichert/Library/buildout/eggs/pytest-2.4.2-py2.7.egg/_pytest/core.py", line 379, in _docall
INTERNALERROR>     res = mc.execute()
INTERNALERROR>   File "/Users/wichert/Library/buildout/eggs/pytest-2.4.2-py2.7.egg/_pytest/core.py", line 297, in execute
INTERNALERROR>     res = method(**kwargs)
INTERNALERROR>   File "/Users/wichert/Library/buildout/eggs/pytest-2.4.2-py2.7.egg/_pytest/runner.py", line 62, in pytest_runtest_protocol
INTERNALERROR>     runtestprotocol(item, nextitem=nextitem)
INTERNALERROR>   File "/Users/wichert/Library/buildout/eggs/pytest-2.4.2-py2.7.egg/_pytest/runner.py", line 72, in runtestprotocol
INTERNALERROR>     reports.append(call_and_report(item, "call", log))
INTERNALERROR>   File "/Users/wichert/Library/buildout/eggs/pytest-2.4.2-py2.7.egg/_pytest/runner.py", line 108, in call_and_report
INTERNALERROR>     report = hook.pytest_runtest_makereport(item=item, call=call)
INTERNALERROR>   File "/Users/wichert/Library/buildout/eggs/pytest-2.4.2-py2.7.egg/_pytest/main.py", line 161, in call_matching_hooks
INTERNALERROR>     return hookmethod.pcall(plugins, **kwargs)
INTERNALERROR>   File "/Users/wichert/Library/buildout/eggs/pytest-2.4.2-py2.7.egg/_pytest/core.py", line 372, in pcall
INTERNALERROR>     return self._docall(methods, kwargs)
INTERNALERROR>   File "/Users/wichert/Library/buildout/eggs/pytest-2.4.2-py2.7.egg/_pytest/core.py", line 379, in _docall
INTERNALERROR>     res = mc.execute()
INTERNALERROR>   File "/Users/wichert/Library/buildout/eggs/pytest-2.4.2-py2.7.egg/_pytest/core.py", line 297, in execute
INTERNALERROR>     res = method(**kwargs)
INTERNALERROR>   File "/Users/wichert/Library/buildout/eggs/pytest_ipdb-0.1_prerelease-py2.7.egg/pytestipdb/ptipdb.py", line 73, in pytest_runtest_makereport
INTERNALERROR>     post_mortem(tb)
INTERNALERROR>   File "/Users/wichert/Library/buildout/eggs/pytest_ipdb-0.1_prerelease-py2.7.egg/pytestipdb/ptipdb.py", line 88, in post_mortem
INTERNALERROR>     ip = IPython.core.ipapi.get()
INTERNALERROR> AttributeError: 'module' object has no attribute 'ipapi'
```

**Comment by mverteuil** [comment]
Please see the README: this project has been end-of-lifed.

I recommend that you use pdbpp as an easier and better alternative:
https://pypi.python.org/pypi/pdbpp/
