### ISSUE TITLE
Tests fail with pytest>2.5.2

### ISSUE THREAD

**Issue by msabramo** [mverteuil/pytest-ipdb#25]
I can only get tox tests to pass if I pin `pytest==2.5.2` in `tox.ini`.

With newer versions of pytest (e.g.: 2.6.1), I get failures like:

```
❯ .tox/py27/bin/py.test --maxfail=1
============================================================================= test session starts ==============================================================================
platform darwin -- Python 2.7.6 -- py-1.4.23 -- pytest-2.6.1
plugins: ipdb
collected 6 items

test_pytest_ipdb.py F

=================================================================================== FAILURES ===================================================================================
__________________________________________________________________________ test_post_mortem[default] ___________________________________________________________________________

testdir = <TmpTestdir local('/private/var/folders/gw/w0clrs515zx9x_55zgtpv4mm0000gp/T/pytest-63/testdir/test_post_mortem0')>
option = <test_pytest_ipdb.Option object at 0x103ef4f50>

    def test_post_mortem(testdir, option):
        testdir.makepyfile(
            """
            def test_func():
                assert 0
            """
        )

        result = testdir.runpytest(*option.args)

        if option.no_ipdb:
            result.stdout.fnmatch_lines(['(Pdb) '])
        else:
>           result.stdout.fnmatch_lines(['ipdb> '])
E           Failed: remains unmatched: 'ipdb> ', see stderr

/Users/marca/dev/git-repos/pytest-ipdb/test_pytest_ipdb.py:40: Failed
----------------------------------------------------------------------------- Captured stdout call -----------------------------------------------------------------------------
running ['/Users/marca/dev/git-repos/pytest-ipdb/.tox/py27/bin/python', '/Users/marca/dev/git-repos/pytest-ipdb/.tox/py27/lib/python2.7/site-packages/pytest.py', '--basetemp=/private/var/folders/gw/w0clrs515zx9x_55zgtpv4mm0000gp/T/pytest-63/testdir/test_post_mortem0/runpytest-0', '--ipdb'] curdir= /private/var/folders/gw/w0clrs515zx9x_55zgtpv4mm0000gp/T/pytest-63/testdir/test_post_mortem0
============================= test session starts ==============================
platform darwin -- Python 2.7.6 -- py-1.4.23 -- pytest-2.6.1
plugins: ipdb
collected 1 items

test_post_mortem.py
>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>> traceback >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>

    def test_func():
>       assert 0
E       assert 0

test_post_mortem.py:2: AssertionError
>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>> entering PDB >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>

INTERNALERROR> Traceback (most recent call last):
INTERNALERROR>   File "/Users/marca/dev/git-repos/pytest-ipdb/.tox/py27/lib/python2.7/site-packages/_pytest/main.py", line 84, in wrap_session
INTERNALERROR>     doit(config, session)
INTERNALERROR>   File "/Users/marca/dev/git-repos/pytest-ipdb/.tox/py27/lib/python2.7/site-packages/_pytest/main.py", line 122, in _main
INTERNALERROR>     config.hook.pytest_runtestloop(session=session)
INTERNALERROR>   File "/Users/marca/dev/git-repos/pytest-ipdb/.tox/py27/lib/python2.7/site-packages/_pytest/core.py", line 413, in __call__
INTERNALERROR>     return self._docall(methods, kwargs)
INTERNALERROR>   File "/Users/marca/dev/git-repos/pytest-ipdb/.tox/py27/lib/python2.7/site-packages/_pytest/core.py", line 424, in _docall
INTERNALERROR>     res = mc.execute()
INTERNALERROR>   File "/Users/marca/dev/git-repos/pytest-ipdb/.tox/py27/lib/python2.7/site-packages/_pytest/core.py", line 315, in execute
INTERNALERROR>     res = method(**kwargs)
INTERNALERROR>   File "/Users/marca/dev/git-repos/pytest-ipdb/.tox/py27/lib/python2.7/site-packages/_pytest/main.py", line 142, in pytest_runtestloop
INTERNALERROR>     item.config.hook.pytest_runtest_protocol(item=item, nextitem=nextitem)
INTERNALERROR>   File "/Users/marca/dev/git-repos/pytest-ipdb/.tox/py27/lib/python2.7/site-packages/_pytest/core.py", line 413, in __call__
INTERNALERROR>     return self._docall(methods, kwargs)
INTERNALERROR>   File "/Users/marca/dev/git-repos/pytest-ipdb/.tox/py27/lib/python2.7/site-packages/_pytest/core.py", line 424, in _docall
INTERNALERROR>     res = mc.execute()
INTERNALERROR>   File "/Users/marca/dev/git-repos/pytest-ipdb/.tox/py27/lib/python2.7/site-packages/_pytest/core.py", line 315, in execute
INTERNALERROR>     res = method(**kwargs)
INTERNALERROR>   File "/Users/marca/dev/git-repos/pytest-ipdb/.tox/py27/lib/python2.7/site-packages/_pytest/runner.py", line 65, in pytest_runtest_protocol
INTERNALERROR>     runtestprotocol(item, nextitem=nextitem)
INTERNALERROR>   File "/Users/marca/dev/git-repos/pytest-ipdb/.tox/py27/lib/python2.7/site-packages/_pytest/runner.py", line 75, in runtestprotocol
INTERNALERROR>     reports.append(call_and_report(item, "call", log))
INTERNALERROR>   File "/Users/marca/dev/git-repos/pytest-ipdb/.tox/py27/lib/python2.7/site-packages/_pytest/runner.py", line 111, in call_and_report
INTERNALERROR>     report = hook.pytest_runtest_makereport(item=item, call=call)
INTERNALERROR>   File "/Users/marca/dev/git-repos/pytest-ipdb/.tox/py27/lib/python2.7/site-packages/_pytest/main.py", line 166, in call_matching_hooks
INTERNALERROR>     return hookmethod.pcall(plugins, **kwargs)
INTERNALERROR>   File "/Users/marca/dev/git-repos/pytest-ipdb/.tox/py27/lib/python2.7/site-packages/_pytest/core.py", line 417, in pcall
INTERNALERROR>     return self._docall(methods, kwargs)
INTERNALERROR>   File "/Users/marca/dev/git-repos/pytest-ipdb/.tox/py27/lib/python2.7/site-packages/_pytest/core.py", line 424, in _docall
INTERNALERROR>     res = mc.execute()
INTERNALERROR>   File "/Users/marca/dev/git-repos/pytest-ipdb/.tox/py27/lib/python2.7/site-packages/_pytest/core.py", line 315, in execute
INTERNALERROR>     res = method(**kwargs)
INTERNALERROR>   File "/Users/marca/dev/git-repos/pytest-ipdb/.tox/py27/lib/python2.7/site-packages/pytestipdb/ptipdb.py", line 111, in pytest_runtest_makereport
INTERNALERROR>     post_mortem(tb)
INTERNALERROR>   File "/Users/marca/dev/git-repos/pytest-ipdb/.tox/py27/lib/python2.7/site-packages/pytestipdb/ptipdb.py", line 123, in post_mortem
INTERNALERROR>     shell = IPython.InteractiveShell.instance()
INTERNALERROR>   File "/Users/marca/dev/git-repos/pytest-ipdb/.tox/py27/lib/python2.7/site-packages/IPython/config/configurable.py", line 354, in instance
INTERNALERROR>     inst = cls(*args, **kwargs)
INTERNALERROR>   File "/Users/marca/dev/git-repos/pytest-ipdb/.tox/py27/lib/python2.7/site-packages/IPython/core/interactiveshell.py", line 483, in __init__
INTERNALERROR>     self.init_readline()
INTERNALERROR>   File "/Users/marca/dev/git-repos/pytest-ipdb/.tox/py27/lib/python2.7/site-packages/IPython/core/interactiveshell.py", line 1884, in init_readline
INTERNALERROR>     self.refill_readline_hist()
INTERNALERROR>   File "/Users/marca/dev/git-repos/pytest-ipdb/.tox/py27/lib/python2.7/site-packages/IPython/core/interactiveshell.py", line 1893, in refill_readline_hist
INTERNALERROR>     stdin_encoding = sys.stdin.encoding or "utf-8"
INTERNALERROR> AttributeError: DontReadFromInput instance has no attribute 'encoding'

===============================  in 0.04 seconds ===============================
----------------------------------------------------------------------------- Captured stderr call -----------------------------------------------------------------------------
nomatch: 'ipdb> '
    and: u'============================= test session starts =============================='
    and: u'platform darwin -- Python 2.7.6 -- py-1.4.23 -- pytest-2.6.1'
    and: u'plugins: ipdb'
    and: u'collected 1 items'
    and: u''
    and: u'test_post_mortem.py '
    and: u'>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>> traceback >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>'
    and: u''
    and: u'    def test_func():'
    and: u'>       assert 0'
    and: u'E       assert 0'
    and: u''
    and: u'test_post_mortem.py:2: AssertionError'
    and: u'>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>> entering PDB >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>'
    and: u''
    and: u'INTERNALERROR> Traceback (most recent call last):'
    and: u'INTERNALERROR>   File "/Users/marca/dev/git-repos/pytest-ipdb/.tox/py27/lib/python2.7/site-packages/_pytest/main.py", line 84, in wrap_session'
    and: u'INTERNALERROR>     doit(config, session)'
    and: u'INTERNALERROR>   File "/Users/marca/dev/git-repos/pytest-ipdb/.tox/py27/lib/python2.7/site-packages/_pytest/main.py", line 122, in _main'
    and: u'INTERNALERROR>     config.hook.pytest_runtestloop(session=session)'
    and: u'INTERNALERROR>   File "/Users/marca/dev/git-repos/pytest-ipdb/.tox/py27/lib/python2.7/site-packages/_pytest/core.py", line 413, in __call__'
    and: u'INTERNALERROR>     return self._docall(methods, kwargs)'
    and: u'INTERNALERROR>   File "/Users/marca/dev/git-repos/pytest-ipdb/.tox/py27/lib/python2.7/site-packages/_pytest/core.py", line 424, in _docall'
    and: u'INTERNALERROR>     res = mc.execute()'
    and: u'INTERNALERROR>   File "/Users/marca/dev/git-repos/pytest-ipdb/.tox/py27/lib/python2.7/site-packages/_pytest/core.py", line 315, in execute'
    and: u'INTERNALERROR>     res = method(**kwargs)'
    and: u'INTERNALERROR>   File "/Users/marca/dev/git-repos/pytest-ipdb/.tox/py27/lib/python2.7/site-packages/_pytest/main.py", line 142, in pytest_runtestloop'
    and: u'INTERNALERROR>     item.config.hook.pytest_runtest_protocol(item=item, nextitem=nextitem)'
    and: u'INTERNALERROR>   File "/Users/marca/dev/git-repos/pytest-ipdb/.tox/py27/lib/python2.7/site-packages/_pytest/core.py", line 413, in __call__'
    and: u'INTERNALERROR>     return self._docall(methods, kwargs)'
    and: u'INTERNALERROR>   File "/Users/marca/dev/git-repos/pytest-ipdb/.tox/py27/lib/python2.7/site-packages/_pytest/core.py", line 424, in _docall'
    and: u'INTERNALERROR>     res = mc.execute()'
    and: u'INTERNALERROR>   File "/Users/marca/dev/git-repos/pytest-ipdb/.tox/py27/lib/python2.7/site-packages/_pytest/core.py", line 315, in execute'
    and: u'INTERNALERROR>     res = method(**kwargs)'
    and: u'INTERNALERROR>   File "/Users/marca/dev/git-repos/pytest-ipdb/.tox/py27/lib/python2.7/site-packages/_pytest/runner.py", line 65, in pytest_runtest_protocol'
    and: u'INTERNALERROR>     runtestprotocol(item, nextitem=nextitem)'
    and: u'INTERNALERROR>   File "/Users/marca/dev/git-repos/pytest-ipdb/.tox/py27/lib/python2.7/site-packages/_pytest/runner.py", line 75, in runtestprotocol'
    and: u'INTERNALERROR>     reports.append(call_and_report(item, "call", log))'
    and: u'INTERNALERROR>   File "/Users/marca/dev/git-repos/pytest-ipdb/.tox/py27/lib/python2.7/site-packages/_pytest/runner.py", line 111, in call_and_report'
    and: u'INTERNALERROR>     report = hook.pytest_runtest_makereport(item=item, call=call)'
    and: u'INTERNALERROR>   File "/Users/marca/dev/git-repos/pytest-ipdb/.tox/py27/lib/python2.7/site-packages/_pytest/main.py", line 166, in call_matching_hooks'
    and: u'INTERNALERROR>     return hookmethod.pcall(plugins, **kwargs)'
    and: u'INTERNALERROR>   File "/Users/marca/dev/git-repos/pytest-ipdb/.tox/py27/lib/python2.7/site-packages/_pytest/core.py", line 417, in pcall'
    and: u'INTERNALERROR>     return self._docall(methods, kwargs)'
    and: u'INTERNALERROR>   File "/Users/marca/dev/git-repos/pytest-ipdb/.tox/py27/lib/python2.7/site-packages/_pytest/core.py", line 424, in _docall'
    and: u'INTERNALERROR>     res = mc.execute()'
    and: u'INTERNALERROR>   File "/Users/marca/dev/git-repos/pytest-ipdb/.tox/py27/lib/python2.7/site-packages/_pytest/core.py", line 315, in execute'
    and: u'INTERNALERROR>     res = method(**kwargs)'
    and: u'INTERNALERROR>   File "/Users/marca/dev/git-repos/pytest-ipdb/.tox/py27/lib/python2.7/site-packages/pytestipdb/ptipdb.py", line 111, in pytest_runtest_makereport'
    and: u'INTERNALERROR>     post_mortem(tb)'
    and: u'INTERNALERROR>   File "/Users/marca/dev/git-repos/pytest-ipdb/.tox/py27/lib/python2.7/site-packages/pytestipdb/ptipdb.py", line 123, in post_mortem'
    and: u'INTERNALERROR>     shell = IPython.InteractiveShell.instance()'
    and: u'INTERNALERROR>   File "/Users/marca/dev/git-repos/pytest-ipdb/.tox/py27/lib/python2.7/site-packages/IPython/config/configurable.py", line 354, in instance'
    and: u'INTERNALERROR>     inst = cls(*args, **kwargs)'
    and: u'INTERNALERROR>   File "/Users/marca/dev/git-repos/pytest-ipdb/.tox/py27/lib/python2.7/site-packages/IPython/core/interactiveshell.py", line 483, in __init__'
    and: u'INTERNALERROR>     self.init_readline()'
    and: u'INTERNALERROR>   File "/Users/marca/dev/git-repos/pytest-ipdb/.tox/py27/lib/python2.7/site-packages/IPython/core/interactiveshell.py", line 1884, in init_readline'
    and: u'INTERNALERROR>     self.refill_readline_hist()'
    and: u'INTERNALERROR>   File "/Users/marca/dev/git-repos/pytest-ipdb/.tox/py27/lib/python2.7/site-packages/IPython/core/interactiveshell.py", line 1893, in refill_readline_hist'
    and: u'INTERNALERROR>     stdin_encoding = sys.stdin.encoding or "utf-8"'
    and: u"INTERNALERROR> AttributeError: DontReadFromInput instance has no attribute 'encoding'"
    and: u''
    and: u'===============================  in 0.04 seconds ==============================='
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!! Interrupted: stopping after 1 failures !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
=========================================================================== 1 failed in 0.5
```

Cc: @mverteuil, @davidszotten

**Comment by mverteuil** [comment]
Please see the README: this project has been end-of-lifed.

I recommend that you use pdbpp as an easier and better alternative:
https://pypi.python.org/pypi/pdbpp/
