### ISSUE TITLE
Calling with pytest --ipdb creates odd error with stdout on python 3.4

### ISSUE THREAD

**Issue by spool** [mverteuil/pytest-ipdb#31]
Hi. Not really sure what this error means. I intentionally used an `assert False` statement to drop into ipdb and ended up with this error.

```python
ipdb>
INTERNALERROR> Traceback (most recent call last):
INTERNALERROR>   File "/path/to/venv/lib/python3.4/site-packages/_pytest/main.py", line 84, in wrap_session
INTERNALERROR>     doit(config, session)
INTERNALERROR>   File "/path/to/venv/lib/python3.4/site-packages/_pytest/main.py", line 122, in _main
INTERNALERROR>     config.hook.pytest_runtestloop(session=session)
INTERNALERROR>   File "/path/to/venv/lib/python3.4/site-packages/_pytest/core.py", line 413, in __call__
INTERNALERROR>     return self._docall(methods, kwargs)
INTERNALERROR>   File "/path/to/venv/lib/python3.4/site-packages/_pytest/core.py", line 424, in _docall
INTERNALERROR>     res = mc.execute()
INTERNALERROR>   File "/path/to/venv/lib/python3.4/site-packages/_pytest/core.py", line 315, in execute
INTERNALERROR>     res = method(**kwargs)
INTERNALERROR>   File "/path/to/venv/lib/python3.4/site-packages/_pytest/main.py", line 142, in pytest_runtestloop
INTERNALERROR>     item.config.hook.pytest_runtest_protocol(item=item, nextitem=nextitem)
INTERNALERROR>   File "/path/to/venv/lib/python3.4/site-packages/_pytest/core.py", line 413, in __call__
INTERNALERROR>     return self._docall(methods, kwargs)
INTERNALERROR>   File "/path/to/venv/lib/python3.4/site-packages/_pytest/core.py", line 424, in _docall
INTERNALERROR>     res = mc.execute()
INTERNALERROR>   File "/path/to/venv/lib/python3.4/site-packages/_pytest/core.py", line 315, in execute
INTERNALERROR>     res = method(**kwargs)
INTERNALERROR>   File "/path/to/venv/lib/python3.4/site-packages/_pytest/runner.py", line 65, in pytest_runtest_protocol
INTERNALERROR>     runtestprotocol(item, nextitem=nextitem)
INTERNALERROR>   File "/path/to/venv/lib/python3.4/site-packages/_pytest/runner.py", line 75, in runtestprotocol
INTERNALERROR>     reports.append(call_and_report(item, "call", log))
INTERNALERROR>   File "/path/to/venv/lib/python3.4/site-packages/_pytest/runner.py", line 111, in call_and_report
INTERNALERROR>     report = hook.pytest_runtest_makereport(item=item, call=call)
INTERNALERROR>   File "/path/to/venv/lib/python3.4/site-packages/_pytest/main.py", line 167, in call_matching_hooks
INTERNALERROR>     return hookmethod.pcall(plugins, **kwargs)
INTERNALERROR>   File "/path/to/venv/lib/python3.4/site-packages/_pytest/core.py", line 417, in pcall
INTERNALERROR>     return self._docall(methods, kwargs)
INTERNALERROR>   File "/path/to/venv/lib/python3.4/site-packages/_pytest/core.py", line 424, in _docall
INTERNALERROR>     res = mc.execute()
INTERNALERROR>   File "/path/to/venv/lib/python3.4/site-packages/_pytest/core.py", line 315, in execute
INTERNALERROR>     res = method(**kwargs)
INTERNALERROR>   File "/path/to/venv/lib/python3.4/site-packages/pytestipdb/ptipdb.py", line 111, in pytest_runtest_makereport
INTERNALERROR>     post_mortem(tb)
INTERNALERROR>   File "/path/to/venv/lib/python3.4/site-packages/pytestipdb/ptipdb.py", line 139, in post_mortem
INTERNALERROR>     p.interaction(frame, tb)
INTERNALERROR>   File "/path/to/venv/lib/python3.4/site-packages/IPython/core/debugger.py", line 278, in interaction
INTERNALERROR>     OldPdb.interaction(self, frame, traceback)
INTERNALERROR>   File "/usr/local/Cellar/python3/3.4.2_1/Frameworks/Python.framework/Versions/3.4/lib/python3.4/pdb.py", line 346, in interaction
INTERNALERROR>     self._cmdloop()
INTERNALERROR>   File "/usr/local/Cellar/python3/3.4.2_1/Frameworks/Python.framework/Versions/3.4/lib/python3.4/pdb.py", line 319, in _cmdloop
INTERNALERROR>     self.cmdloop()
INTERNALERROR>   File "/usr/local/Cellar/python3/3.4.2_1/Frameworks/Python.framework/Versions/3.4/lib/python3.4/cmd.py", line 126, in cmdloop
INTERNALERROR>     line = input(self.prompt)
INTERNALERROR>   File "/path/to/venv/lib/python3.4/site-packages/_pytest/capture.py", line 435, in read
INTERNALERROR>     raise IOError("reading from stdin while output is captured")
INTERNALERROR> OSError: reading from stdin while output is captured
```

**Comment by saurabh-fueled** [comment]
This seems to have been fixed in the latest version of pytest. I was using `pytest-ipdb==0.1-prerelease2` from pypi 

@mverteuil is there any plans for releasing updated pytest-ipdb to pypi[1]?

[1] https://pypi.python.org/pypi/pytest-ipdb

**Comment by qba73** [comment]
I am getting the same error using python3.4.0 3.4.2. Local builds and builds on Travis hangs:
local:

```
NTERNALERROR>     return self._docall(self.methods, kwargs)
INTERNALERROR>   File "/home/jakub/venvs/cipy3/lib/python3.4/site-packages/_pytest/core.py", line 528, in _docall
INTERNALERROR>     firstresult=self.firstresult).execute()
INTERNALERROR>   File "/home/jakub/venvs/cipy3/lib/python3.4/site-packages/_pytest/core.py", line 393, in execute
INTERNALERROR>     return wrapped_call(method(*args), self.execute)
INTERNALERROR>   File "/home/jakub/venvs/cipy3/lib/python3.4/site-packages/_pytest/core.py", line 107, in wrapped_call
INTERNALERROR>     call_outcome = CallOutcome(func)
INTERNALERROR>   File "/home/jakub/venvs/cipy3/lib/python3.4/site-packages/_pytest/core.py", line 137, in get_result
INTERNALERROR>     raise ex[1].with_traceback(ex[2])
INTERNALERROR>   File "/home/jakub/venvs/cipy3/lib/python3.4/site-packages/_pytest/core.py", line 123, in __init__
INTERNALERROR>     self.result = func()
INTERNALERROR>   File "/home/jakub/venvs/cipy3/lib/python3.4/site-packages/_pytest/core.py", line 394, in execute
INTERNALERROR>     res = method(*args)
INTERNALERROR>   File "/home/jakub/venvs/cipy3/lib/python3.4/site-packages/_pytest/runner.py", line 65, in pytest_runtest_protocol
INTERNALERROR>     runtestprotocol(item, nextitem=nextitem)
INTERNALERROR>   File "/home/jakub/venvs/cipy3/lib/python3.4/site-packages/_pytest/runner.py", line 80, in runtestprotocol
INTERNALERROR>     if hasrequest:
INTERNALERROR>   File "/home/jakub/venvs/cipy3/lib/python3.4/site-packages/_pytest/runner.py", line 80, in runtestprotocol
INTERNALERROR>     if hasrequest:
INTERNALERROR>   File "/usr/lib/python3.4/bdb.py", line 48, in trace_dispatch
INTERNALERROR>     return self.dispatch_line(frame)
INTERNALERROR>   File "/usr/lib/python3.4/bdb.py", line 66, in dispatch_line
INTERNALERROR>     self.user_line(frame)
INTERNALERROR>   File "/usr/lib/python3.4/pdb.py", line 259, in user_line
INTERNALERROR>     self.interaction(frame, None)
INTERNALERROR>   File "/usr/lib/python3.4/pdb.py", line 346, in interaction
INTERNALERROR>     self._cmdloop()
INTERNALERROR>   File "/usr/lib/python3.4/pdb.py", line 319, in _cmdloop
INTERNALERROR>     self.cmdloop()
INTERNALERROR>   File "/usr/lib/python3.4/cmd.py", line 126, in cmdloop
INTERNALERROR>     line = input(self.prompt)
INTERNALERROR>   File "/home/jakub/venvs/cipy3/lib/python3.4/site-packages/_pytest/capture.py", line 430, in read
INTERNALERROR>     raise IOError("reading from stdin while output is captured")
INTERNALERROR> OSError: reading from stdin while output is captured

============================================================== 15 passed in 158.64 seconds ===============================================================
```

Travis: 
https://travis-ci.org/qba73/circleclient/jobs/56529032

I use following packages:

```
pytest==2.7.0
pytest-httpretty==0.2.0
requests==2.6.0
```

I would appreciate any help that could point me what causes this problem on Python 3.4

**Comment by mverteuil** [comment]
Please see the README: this project has been end-of-lifed.

I recommend that you use pdbpp as an easier and better alternative:
https://pypi.python.org/pypi/pdbpp/
